name: ci
on:
  pull_request:
  release:
    types: [published]
  push:
    tags:
    branches:
      - main
      - develop

env:
  VERBOSE: 1

jobs:
  linux:
    name: Linux gcc-14 Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Project Name
        uses: cardinalby/export-env-action@v2
        with:
          envFile: '.github/constants.env'

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.3'
          arch: 'linux_gcc_64'
          install-deps: true

      - name: Install libclang
        run: sudo apt-get update -qq && sudo apt-get install -y libclang-dev llvm-dev

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc-14
          cmake: true
          ninja: true
          vcpkg: false
          ccache: true
          clangtidy: '19.1.1'
          cppcheck: false
          gcovr: false

      - name: Configure CMake
        shell: bash
        run: |
          cmake -S . -B ./build -G "Ninja Multi-Config" \
            -D CMAKE_PREFIX_PATH:PATH="$QT_ROOT_DIR" \
            -D ${{ env.PROJECT_NAME }}_ENABLE_IPO=OFF \
            -D CMAKE_BUILD_TYPE:STRING=Release \
            -D ${{ env.PROJECT_NAME }}_PACKAGING_MAINTAINER_MODE:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_CLANG_TIDY:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_CPPCHECK:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_COVERAGE:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_WARNINGS_AS_ERRORS:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_SANITIZER_ADDRESS:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_SANITIZER_UNDEFINED:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_SANITIZER_LEAK:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_SANITIZER_THREAD:BOOL=OFF \
            -DGIT_SHA:STRING=${{ github.sha }}

      - name: Build
        run: cmake --build ./build --config Release

      - name: Test
        working-directory: ./build
        run: ctest -C Release

      - name: CPack
        working-directory: ./build
        run: cpack -C Release -G DEB

  macos:
    name: macOS llvm-19.1.1 Release
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Project Name
        uses: cardinalby/export-env-action@v2
        with:
          envFile: '.github/constants.env'

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.3'
          arch: 'clang_64'
          install-deps: true

      - name: Install libclang
        run: brew install llvm

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm-19.1.1
          cmake: true
          ninja: true
          vcpkg: false
          ccache: true
          clangtidy: '19.1.1'
          cppcheck: false
          gcovr: false

      - name: Configure CMake
        shell: bash
        run: |
          cmake -S . -B ./build -G "Ninja Multi-Config" \
            -D CMAKE_PREFIX_PATH:PATH="$QT_ROOT_DIR" \
            -D ${{ env.PROJECT_NAME }}_ENABLE_IPO=OFF \
            -D CMAKE_BUILD_TYPE:STRING=Release \
            -D ${{ env.PROJECT_NAME }}_PACKAGING_MAINTAINER_MODE:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_CLANG_TIDY:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_CPPCHECK:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_COVERAGE:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_WARNINGS_AS_ERRORS:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_SANITIZER_ADDRESS:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_SANITIZER_UNDEFINED:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_SANITIZER_LEAK:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_SANITIZER_THREAD:BOOL=OFF \
            -DGIT_SHA:STRING=${{ github.sha }}

      - name: Build
        run: cmake --build ./build --config Release

      - name: Test
        working-directory: ./build
        run: ctest -C Release

      - name: CPack
        working-directory: ./build
        run: cpack -C Release -G TBZ2

  windows:
    name: Windows MSVC Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Project Name
        uses: cardinalby/export-env-action@v2
        with:
          envFile: '.github/constants.env'

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.3'
          arch: 'win64_msvc2019_64'
          install-deps: true

      - name: Install libclang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: '19.1.0'

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: msvc
          vcvarsall: true
          cmake: true
          ninja: true
          vcpkg: false
          ccache: false
          clangtidy: '19.1.1'
          cppcheck: false
          gcovr: false
          opencppcoverage: true

      - name: Configure CMake
        shell: bash
        env:
          CC: cl
          CXX: cl
        run: |
          cmake -S . -B ./build -G "Ninja Multi-Config" \
            -D CMAKE_PREFIX_PATH:PATH="$QT_ROOT_DIR" \
            -D ${{ env.PROJECT_NAME }}_ENABLE_IPO=OFF \
            -D CMAKE_BUILD_TYPE:STRING=Release \
            -D ${{ env.PROJECT_NAME }}_PACKAGING_MAINTAINER_MODE:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_CLANG_TIDY:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_CPPCHECK:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_COVERAGE:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_WARNINGS_AS_ERRORS:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_SANITIZER_ADDRESS:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_SANITIZER_UNDEFINED:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_SANITIZER_LEAK:BOOL=OFF \
            -D ${{ env.PROJECT_NAME }}_ENABLE_SANITIZER_THREAD:BOOL=OFF \
            -DGIT_SHA:STRING=${{ github.sha }}

      - name: Build
        run: cmake --build ./build --config Release

      - name: Test
        working-directory: ./build
        run: ctest -C Release

      - name: CPack
        working-directory: ./build
        run: cpack -C Release -G ZIP
